baseURL = 'https://digital-ai-finance.github.io/Green-Finance/'
languageCode = 'en-us'
title = 'GREEN FINANCE - Erasmus+ Project'
theme = 'hugo-book'

# For private repo with GitHub Pages
publishDir = 'public'
canonifyURLs = true

[params]
  description = 'Advancing Higher Education for Sustainable Growth in Southeast Asia'
  author = 'GREEN FINANCE Consortium'
  images = ['images/logos/eu_cofunded.png']
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'project'
  BookRepo = 'https://github.com/Digital-AI-Finance/green-finance'
  BookEditPath = 'edit/main'
  BookDateFormat = 'January 2, 2006'

[menu]
# Top menu (before sidebar content)
[[menu.before]]
  name = 'Home'
  url = '/'
  weight = 1

[[menu.before]]
  name = 'Project'
  url = '/project/'
  weight = 2

[[menu.before]]
  name = 'Course'
  url = '/course/'
  weight = 3

[[menu.before]]
  name = 'Slides'
  url = '/slides/'
  weight = 4

# Bottom menu (after sidebar content)
[[menu.after]]
  name = 'Partners'
  url = '/project/partners/'
  weight = 1

[[menu.after]]
  name = 'Work Packages'
  url = '/project/work-packages/'
  weight = 2

[[menu.after]]
  name = 'Timeline'
  url = '/project/timeline/'
  weight = 3

[[menu.after]]
  name = 'Team'
  url = '/project/team/'
  weight = 4

[[menu.after]]
  name = 'News'
  url = '/project/news/'
  weight = 5

[[menu.after]]
  name = 'GitHub'
  url = 'https://github.com/Digital-AI-Finance/green-finance'
  weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML']
  page = ['HTML']
